# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'
 inhibit_all_warnings!

target 'TestBB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestBB
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'NudeIn'
  pod 'SDWebImage'

end
